require "settings.user"
require"settings.vim_plug"
require"settings.colorschema"
require"settings.plugins"
require"settings.lsp"
require"settings.treesitter"
require"settings.cmp"
require"settings.lsp_08"
