require("settings.plugins.devicons")
require("settings.plugins.nerdtree")
require("settings.plugins.telescope")
require("settings.plugins.lualine")
require("settings.plugins.hopnvim")
require("settings.plugins.autopairs")
require("settings.plugins.notify")
require("settings.plugins.closetag")
