require("settings.plugins.closetag")
require("settings.plugins.devicons")
require("settings.plugins.nerdtree")
require("settings.plugins.telescope")
require("settings.plugins.lualine")
require("settings.plugins.hopnvim")
