--require("settings.plugins.notify")
--require("settings.plugins.devicons")
--require"settings.plugins.nvimtree"
--require("settings.plugins.telescope")
--require "settings.plugins.lualine"
--require("settings.plugins.feline")
--require("plugins.hopnvim")
--require("settings.plugins.autopairs")
--require("settings.plugins.closetag")
